# Generated by Django 2.2.14 on 2020-10-01 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.custom_fields
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200925_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=utils.custom_fields.CustomBigIntegerField(unique=True, validators=[utils.validators.PhoneNumberValidator()], verbose_name='phone number'),
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('verification_code', models.PositiveIntegerField(verbose_name='verification code')),
                ('verify_time', models.DateTimeField(blank=True, null=True, verbose_name='verify_time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verify_codes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Verify code',
                'verbose_name_plural': 'Verify codes',
            },
        ),
    ]
