# Generated by Django 2.2.14 on 2020-10-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201001_1755'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='verifycode',
            index=models.Index(fields=['user', 'verification_code'], name='index_user_code'),
        ),
    ]
