# Generated by Django 2.2.14 on 2020-08-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_enable', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('phone_number', models.BigIntegerField()),
                ('address', models.TextField(blank=True)),
                ('products', models.ManyToManyField(related_name='stores', to='products.Product')),
            ],
        ),
    ]
