# Generated by Django 2.2.14 on 2020-08-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200820_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='phone_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
